version: '3.8'

services:
  api-solid-ex-pg:
    image: bitnami/postgresql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DABASE: apisolid