name: E2E Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: docker
          POSTGRES_USER: docker
          POSTGRES_DB: apisolid
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Run database migrations
      run: npx prisma db push
      env:
        DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"

    - name: Run E2E tests
      run: npm run test:e2e
      env:
        DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"
        JWT_SECRET: "testing-secret-key" 