name: E2E Tests

on:
  pull_request:
    branches: [ main, master, develop ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5433:5432
        env:
          POSTGRES_PASSWORD: docker
          POSTGRES_USER: docker
          POSTGRES_DB: apisolid

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run E2E tests
      run: npm run test:e2e
      env:
        JWT_SECRET: "testing-secret-key" 
        DATABASE_URL: "postgresql://docker:docker@localhost:5433/apisolid?schema=public"